#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class HeaderContent:
  """
  Attributes:
   - seqId
   - servicename
   - attachment
  """

  thrift_spec = (
    None, # 0
    (1, TType.I64, 'seqId', None, None, ), # 1
    (2, TType.STRING, 'servicename', None, None, ), # 2
    (3, TType.MAP, 'attachment', (TType.STRING,None,TType.STRING,None), None, ), # 3
  )

  def __init__(self, seqId=None, servicename=None, attachment=None,):
    self.seqId = seqId
    self.servicename = servicename
    self.attachment = attachment

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I64:
          self.seqId = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.servicename = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.MAP:
          self.attachment = {}
          (_ktype1, _vtype2, _size0 ) = iprot.readMapBegin()
          for _i4 in xrange(_size0):
            _key5 = iprot.readString();
            _val6 = iprot.readString();
            self.attachment[_key5] = _val6
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('HeaderContent')
    if self.seqId is not None:
      oprot.writeFieldBegin('seqId', TType.I64, 1)
      oprot.writeI64(self.seqId)
      oprot.writeFieldEnd()
    if self.servicename is not None:
      oprot.writeFieldBegin('servicename', TType.STRING, 2)
      oprot.writeString(self.servicename)
      oprot.writeFieldEnd()
    if self.attachment is not None:
      oprot.writeFieldBegin('attachment', TType.MAP, 3)
      oprot.writeMapBegin(TType.STRING, TType.STRING, len(self.attachment))
      for kiter7,viter8 in self.attachment.items():
        oprot.writeString(kiter7)
        oprot.writeString(viter8)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.seqId is None:
      raise TProtocol.TProtocolException(message='Required field seqId is unset!')
    if self.servicename is None:
      raise TProtocol.TProtocolException(message='Required field servicename is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.seqId)
    value = (value * 31) ^ hash(self.servicename)
    value = (value * 31) ^ hash(self.attachment)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.items()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
